### ISSUE TITLE
Please inquire about the current availability of this project

### ISSUE THREAD

**Issue by sailthesea** [jdc8/lsp#1]
![image](https://github.com/jdc8/lsp/assets/12014374/75c5aa8e-e4fd-48a7-9782-24fb159d2611)
![image](https://github.com/jdc8/lsp/assets/12014374/1b88fca9-9d2b-4712-bba4-fdbedba0168b)

Hi,I run lsp.tcl directly, hover can do not work, can you help me.

**Comment by jdc8** [comment]
Hi,

This LSP is just a test vehicle for me, nothing like production ready. Sorry about that, but making a LSP for Tcl is a big task.

Kind regards,
Jos.

**Comment by sailthesea** [comment]
OK, thanks.
